### PR TITLE
adding a readme

### PR DESCRIPTION
**Pull request by boland25**
Adding a readme because "SOMEONE" can't live without it

### CODE REVIEW

**Comment by HuangJunye** [comment]
Thanks for adding the resume. I want to add the link to the original QPong repo. I am going to restore the branch and add that.

**Comment by HuangJunye** [comment]
I added the link and instruction to install dependencies. Is it a good idea to learn the branch open for updating readme in the future?

**Comment by boland25** [comment]
no need to leave the branch open because it will be so different from the main branch and it will be a pain to maintain.  easier to start a new branch off its current state at the time when you wnat to make a change

**Comment by HuangJunye** [comment]
Ok, got it. I will delete the branch

**Pull request merged**
